esphome:
  name: esp-fil-pilote-1

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "12379952337abd8fe10f9627996878f3"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.60
    gateway: 192.168.0.1
    subnet: 255.255.255.0
#  output_power: 10dB
  fast_connect: true
#  power_save_mode: light
#  power_save_mode: HIGH

web_server:
  port: 80


captive_portal:
    
sensor:
  - platform: wifi_signal
    name: "WiFi"
    update_interval: 60s  
    
  - platform: uptime
    name: "Uptime"
    update_interval: 60s

deep_sleep:
  run_duration: 1min
  sleep_duration: 10min   