# Commande attrape moustics
#   - mise a jour date/heure par NTP
#   - actionne le relai à 18h00
#   - arrêt relai à 23h00
#   - mesure VCC
#   - mesure tension batterie
#   - deep sleep 5 minutes 
#   
# D0 : wake-up -> RST 
# D4 : mesure température / Hygro
# D5 : relai
# A0 : tension batterie
#



esphome:
  name: esphome-web-c4135f

esp8266:
  board: d1_mini

# Enable logging
logger:
#  level: DEBUG 
#  baud_rate: 115200
  baud_rate: 0
  level: NONE
  
# Enable Home Assistant API
api:

ota:
  password: "bc3d5863ddecd58953528805bd462344"


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.54
    gateway: 192.168.0.1
    subnet: 255.255.255.0
  fast_connect: true
  output_power: 10dB
  power_save_mode: HIGH


  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Esphome-Web-C4135F"
#    password: "zIb84xcHUGbl"

web_server:
  port: 80

captive_portal:
    
switch:
  - platform: gpio
    name: "Relay"
    pin: 5
    id: switch_relay
    
time:
  - platform: homeassistant
    id: homeassistant_time
    
  - platform: sntp
    # ...
    on_time:
      - hours: 18
#        minutes: 0
        then:
          - switch.turn_on: switch_relay
      - hours: 23
#        minutes: 52
        then:
          - switch.turn_off: switch_relay


#deep_sleep:
#  run_duration: 1min
#  sleep_duration: 10min
    
sensor:
  - platform: wifi_signal
    name: "WiFi"
    update_interval: 60s  
    
  - platform: uptime
    name: "Uptime"
    update_interval: 60s


  - platform: dht
    pin: D4
    model: DHT22
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s
    
#  - platform: adc
#    pin: A0
#    name: "Battery Voltage"
#    update_interval: 60s
#    filters:
#      - multiply: 4.01

  - platform: adc
    pin: VCC
    name: "VCC Voltage"
    update_interval: 30s
    
